### ISSUE TITLE
CustomCounters not working anymore since 2.3.4

### ISSUE THREAD

**Issue by no-1-noob** [RileyPrince/CountersPlus#137]
The Functionality of creating custom counters in other mods is not working anymore (They basically do not get recpgnized as existing)

I saw in the commits, that the [CustomCounterFeature.cs](https://github.com/RileyPrince/CountersPlus/commit/800af95356345a4b0f2d4014f99b22d66e599d09#diff-1a6bf580341ab5470be537a86175769b9fedcd6dba46707ad0dcf077ce9d0993) has been deleted in this commit and the IPA.DefineFeature removed from the manifest.

Did this have a reasoning?
I tried to patch it back into C+ and it seems to load CustomCounters just fine (after adding IPA.Definefeature and CustomCounterFeature.cs), but maybe i am overlooking some problem you encounted while fixing C+ for 1.34?

Best regards

**Comment by Caeden117** [comment]
If intentional, this breaks semver and should necessitate a major version bump.

**Comment by RileyPrince** [comment]
Oh? I'll look into it @no-1-noob once I get a chance, apologies for any issues

**Comment by RileyPrince** [comment]
@no-1-noob I can see the issue I had previously, when compiling, I faced an error stating that I hadn't implemented a member for an interface (Initialize), although it was implemented. 

I didn't realize this was actually a core component for counters to work

**Comment by denpadokei** [comment]
This occurs because there is a difference in the versions of Newtonsoft.Json referenced by IPA.Loader and CountersPlus.
You should be able to build by setting the `SpecificVersion` entry in csproj to True and specifying 13.0.0.0.

**Comment by RileyPrince** [comment]
Epic, [2.3.5](https://github.com/RileyPrince/CountersPlus/releases/tag/2.3.5) is out now.
