### ISSUE TITLE
Beatmods upload for v1.34.2

### ISSUE THREAD

**Issue by bleetube** [RileyPrince/CountersPlus#138]
Hello, can you upload this to [beatmods](https://beatmods.com/#/mods) again? I've been using your latest release and it works really well afaict. Thanks!

**Comment by gecastan** [comment]
+1

Since most mods are now compatible again with 1.34.2 there is no point using the 1.29 legacy version. I was just waiting for Counters+ to be compatible again. 

Good job ;-)

**Comment by RileyPrince** [comment]
Heya @bleetube ! I have uploaded it to Beatmods, although it is just sitting in the queue. If I was allowed to review self-uploaded plugins, then I would. But since this is not the case, I have to wait for another Beatmods approver to get to it.

**Comment by RileyPrince** [comment]
Also @gecastan the [latest release](https://github.com/RileyPrince/CountersPlus/releases/tag/2.3.4) works on 1.34.2, you can manually install the plugin and it should work fine :D
